### ISSUE TITLE
Using openh264 to replace x264 in ffmpeg as default

### ISSUE THREAD

**Issue by wqh17101** [PyAV-Org/PyAV#965] opened 2022-04-20 01:24 UTC
## Overview

For x264 is GPL license,which will make the project using it become GPL license.
It is better to use openh264(BSD License) to replace x264 in ffmpeg.

**Comment by wqh17101** [comment] 2022-04-20 03:58
Only process isolation can use GPL component without make the source project GPL.
Such as using it by command line.
So check whether pyav affected by this .
Without process isolation, we should not use GPL component .

**Comment by jlaine** [comment] 2022-04-20 05:04
I think this is a duplicate of #805

**Closed by jlaine** 2022-04-20 05:04 UTC
Labels: enhancement
