### ISSUE TITLE
Support for linux/armv7l

### ISSUE THREAD

**Issue by rprata** [PyAV-Org/PyAV#824] opened 2021-10-26 16:55 UTC
## Overview

Nowadays pyav has `whl` binary for `amd64` and `aarch64` provided by `manylinux2014`. Support to armv7l (raspbian) can be easy to port (according [PEP](https://www.python.org/dev/peps/pep-0599/)).

## Desired Behavior

Support architecture linux/arm/v7 in binary `whl` to facilitate install in raspbian 32bits. Installation in this platform spend much time. 

## Example API

```
None
```

**Comment by jlaine** [comment] 2021-12-29 08:38
Duplicate of #708

**Closed by jlaine** 2021-12-29 08:38 UTC
Labels: enhancement, duplicate
