### ISSUE TITLE
documentation website only covers until release 8.0.2

### ISSUE THREAD

**Issue by jonassmedegaard** [PyAV-Org/PyAV#916] opened 2022-03-24 08:46 UTC
The website https://pyav.org/ is seemingly lagging behind: It lists 8.0.2 as newest release, whereas 9.0.2 is newest release tagged on Github.

**Comment by jlaine** [comment] 2022-03-24 09:40
Duplicate of #913. I don't have control over that website, only @mikeboers does.

**Closed by jlaine** 2022-03-24 09:40 UTC
Labels: bug
