### ISSUE TITLE
Encoding frames error: Errno 22 Invalid Argument

### ISSUE THREAD

**Issue by flewellyn** [PyAV-Org/PyAV#507] opened 2019-04-17 20:33 UTC
I am attempting to create a "preview" of a video, using key frames.  Here is the logic:

```invid = av.open('001.mov')
instream = invid.streams.video[0]

outvid = av.open('001_prev.mov')
outstream = outvid.add_stream(template=instream)

outstream.time_base = instream.time_base

instream.codec_context.skip_frame = 'NONKEY'

for frame in invid.decode(instream):
    packet = outstream.encode(frame)
    outvid.mux(packet)

outvid.close()
```

According to the docs, this should work, but the outtream.encode() call fails with Errno 22.  I have no idea why.  The frame itself is correct: when I use frame.to_image() and save a JPEG, it works just fine.

**Comment by jlaine** [comment] 2019-05-01 21:49
The `Stream.encode` method returns packetS, not a single packet.

Try:

```python

# transcode
for frame in invid.decode(instream):
    for packet in outstream.encode(frame):
        outvid.mux(packet)

# flush encoder
for packet in outstream.encode(None):
    outvid.mux(packet)
```

**Comment by flewellyn** [comment] 2019-05-02 01:07
Hmm, no, that doesn't work either, I'm afraid.  I get the same error.

**Comment by jlaine** [comment] 2019-05-02 12:27
Can you provide us with the file you are using for tests?

**Important** : make sure you are the copyright holder of the file!

**Comment by iyah4888** [comment] 2019-05-10 06:37
I have the exactly same issue as well on pyav-6.2.0.

I'm transcoding, and input frame is decoded as the following object:
<av.VideoFrame #4, pts=2048 yuv420p 1280x720 at 0x7fee6368eee8>
and the output stream is 
<av.VideoStream #0 h264, yuv420p 1280x720 at 0x7fee63c30108>

`
datapath = 'ewkFvB89_AE.00278244_00281414.mp4'
input_ = av.open(datapath)
in_stream_v = input_.streams.video[0]
in_stream_v.thread_type = 'AUTO'

output = av.open('test.mp4', 'w')
out_stream_v = output.add_stream(template=in_stream_v)


for packet in input_.demux(in_stream_v):
    if packet.dts is None:
        continue
        
    print(packet)
    
    for frame in packet.decode():
        for packet_out in out_stream_v.encode(frame):
            output.mux(packet_out)

# Flush stream
# Close the files
`

**Comment by jlaine** [comment] 2019-05-11 06:54
Again: files or it didn't happen.

**Comment by iyah4888** [comment] 2019-05-12 01:51
[video](https://www.dropbox.com/s/ysk3q73xq2i6xdw/ewkFvB89_AE.00278244_00281414.mp4?dl=1
)

This is a part of AVSpeech dataset (This data is licensed by Google LLC under a Creative Commons Attribution 4.0 International License.)
I hope no copy right issue may be applied.

**Comment by jlaine** [comment] 2019-05-14 11:07
I can confirm I get the same error using this minimal code:

```python
import av
  
in_container = av.open('ewkFvB89_AE.00278244_00281414.mp4')
in_stream = in_container.streams.video[0]

out_container = av.open('test.mp4', 'w')
out_stream = out_container.add_stream(template=in_stream)

for frame in in_container.decode(in_stream):
    for packet in out_stream.encode(frame):
        out_container.mux(packet)

for packet in out_stream.encode(None):
    out_container.mux(packet)

out_container.close()
in_container.close()
```

I'm not sure what's going on exactly, but it seems to be related to the use of `template`. If I instead do `out_stream = out_container.add_stream('h264')` I get other errors (non-strictly-monotonic PTS) but I no longer get `[Errno 22] Invalid argument`.

**Comment by iyah4888** [comment] 2019-05-16 03:42
@jlaine Could you look into what happens?

**Comment by jlaine** [comment] 2019-05-16 07:01
I will if I get a chance, I'm not paid for this..

**Comment by MarSoft** [comment] 2020-02-14 20:36
Looks like an issue with `avcodec_copy_context`. According to docs, [it is deprecated](https://libav.org/documentation/doxygen/master/group__lavc__core.html#gae381631ba4fb14f4124575d9ceacb87e). I tried to reimplement it with the recommended approach of `avcodec_parameters_{from,to}_context`, but my Cython knowledge is insufficient for that.

**Comment by alexhutnik** [comment] 2021-01-06 23:40
@MarSoft i've managed to implement it but for some reason regular demux / mux is not working. Only the decode / encode case is working.

**Comment by jlaine** [comment] 2022-03-25 22:29
Duplicate of #730

**Closed by jlaine** 2022-03-25 22:29 UTC
