### ISSUE TITLE
Segmentation fault when playing with a stream's codec context

### ISSUE THREAD

**Issue by ben-111** [PyAV-Org/PyAV#1194] opened 2023-10-28 02:02 UTC
## Overview

This code yields a Segmentation fault:
```
>>> v = av.open('a.mp4', 'w')
>>> s = v.add_stream('h264')
>>> s.codec_context.rate
Fraction(24, 1)
>>> s.codec_context.rate = 30
>>> s
Segmentation fault (core dumped)
```

## Expected behavior

You should handle this edge case correctly (either expect codec_context to change or make it readonly).

## Actual behavior

Your code crashes with a Segmentation Fault.

## Investigation

None.

## Reproduction

See overview.

## Versions

- OS: linux Ubuntu 23.04
- PyAV runtime:
```
PyAV v10.0.0
library configuration: --disable-static --enable-shared --libdir=/tmp/vendor/lib --prefix=/tmp/vendor --disable-alsa --disable-doc --disable-mediafoundation --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-lzma --enable-version3 --enable-zlib
library license: GPL version 3 or later
libavcodec     59. 37.100
libavdevice    59.  7.100
libavfilter     8. 44.100
libavformat    59. 27.100
libavutil      57. 28.100
libswresample   4.  7.100
libswscale      6.  7.100
```
- FFmpeg:
```
ffmpeg version 5.1.2-3ubuntu1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12 (Ubuntu 12.2.0-14ubuntu2)
configuration: --prefix=/usr --extra-version=3ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

## Research

This is just a bug, come on.

## Additional context

Just wanted to see if I can change a stream's CodecContext after the stream's creation, since I don't see a way to create a stream from an existing CodecContext. It's unrelated but if you know how to do that, that would be nice to know too.

**Comment by jlaine** [comment] 2023-10-31 05:00
Could you try building the current code and checking whether this still occurs, as I cannot reproduce it on `main`?

**Comment by jlaine** [comment] 2023-11-01 15:56
Duplicate of #1167

**Closed by jlaine** 2023-11-01 15:56 UTC
Labels: bug, duplicate
